In [1]:
# list5_indices = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
list5 = [30, 31, 32, 31, 35, 34, 33, 33, 34, 32, 31, 32, 32, 34, 36, 35] 
ind = list5.index(32) #gets the first position of occurance of 32
print(ind)

# if I want all of them
israq = [sakib for sakib, razeen in enumerate(list5) if razeen == 32]

# here 'index' represents the positions I want to store
# for a, b => means check a and b variable
# in some_list => where to check
# enumerate() assigns index values with list
# if is the condition, save index when value is 32



# i values of the indices list
print(israq)

# we will learn how to update all 32 to 42 after learning loop structure (for)

2
[2, 9, 11, 12]


In [2]:
list5[11]

32

# Set Methods and Numpy

In [3]:
fruits = {"apple", "banana", "cherry"}

print(type(fruits))

<class 'set'>


In [4]:
# two ways of defining a set
# 1 second brackets{}
names = {'Israq', 'Sakib', 'Razeen'}

# 2 using set() and instert a list
more_names = set(['Israq', 'Sakib', 'Razeen'])

print(type(names))
print(type(more_names))

<class 'set'>
<class 'set'>


In [5]:
# set ignores duplicate

duplicate_names = {'Israq', 'Israq', 'Sakib', 'Razeen'}
print(duplicate_names)

{'Israq', 'Sakib', 'Razeen'}


In [32]:
more_names = set(['Israq', 'Sakib', 'Razeen'])
more_names.add('Kamal')
more_names.add('Irfan')
print(more_names)

# no sort because is does not assign any indices
print(more_names[0]) # not allowed

{'Razeen', 'Sakib', 'Irfan', 'Kamal', 'Israq'}


TypeError: 'set' object is not subscriptable

In [20]:
list5 = [30, 31, 32, 31, 35, 34, 33, 33, 34, 32, 31, 32, 32, 34, 36, 35] 
list5.sort(reverse=True)
print(list5)

[36, 35, 35, 34, 34, 34, 33, 33, 32, 32, 32, 32, 31, 31, 31, 30]


In [21]:
x = {'Israq', 'Israq', 'Sakib', 'Razeen'}
y = {'Razeen', 'Sakib', 'Irfan', 'Kamal', 'Israq'}

diff = x.difference(y) # shows elements of x that are not in y, alt. 'x not y'
rev_diff = y.difference(x)

print(diff)

set()


In [23]:
import sys as s
print(s.version)

3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]


In [26]:
x = {'Israq', 'Israq', 'Sakib', 'Razeen'}
y = {'Razeen', 'Sakib', 'Irfan', 'Kamal', 'Israq'}

print(x.issubset(y)) #is x a subset of y?
print(y.issubset(x))

print(x.issuperset(y)) #is x a superset of y?
print(y.issuperset(x))

True
False
False
True


https://www.w3schools.com/python/python_ref_set.asp

**The mathematical operation notations here are important!**

In [30]:
# notice this tuple characteristic, no brackets mean tuple by default

t = 'Apple', 'Banana', 'Mango'

print(type(t))

<class 'set'>


# Let's Begin Numpy

In [35]:
import numpy as np

In [36]:
a = [[1, 2, 3], [5, 6, 7], [9, 10, 11], [13, 14, 15]] #row by row input
print(a)

[[1, 2, 3], [5, 6, 7], [9, 10, 11], [13, 14, 15]]


In [37]:
array = np.array(a)
print(array)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


* shape
* length
* indexing

In [41]:
sh = array.shape
print(sh)
print(type(sh))

(4, 3)
<class 'tuple'>


In [42]:
#if I just need the number of rows
sh[0] # first element of shape tuple is row

4

In [43]:
len(array) # always returns the number of rows

4

In [45]:
t_array = array.T
print(t_array)
print(t_array.shape)
len(t_array)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]
(3, 4)


3

In [47]:
array[:]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [52]:
# get column 2
array[:,2]

array([ 3,  7, 11, 15])

In [53]:
array[2,2]
# same thing is array[:,2][2]

11

In [57]:
pattern = [
    [1, 2, 3, 1, 2, 3],
    [5, 6, 7, 5, 6, 7],
    [9, 10, 11, 9, 10, 11],
    [13, 14, 15, 13, 14, 15],
    [1, 2, 3, 1, 2, 3],
    [5, 6, 7, 5, 6, 7],
    [9, 10, 11, 9, 10, 11],
    [13, 14, 15, 13, 14, 15]
]

pattern_array = np.array(pattern)
pattern_array[:, 4]

array([ 2,  6, 10, 14,  2,  6, 10, 14])

In [58]:
print(type(pattern))
print(type(pattern_array))

<class 'list'>
<class 'numpy.ndarray'>
